var scheduleData = {
	  "events": [
	    {
            "dtstart": "2010-09-25T09:15:00", 
            "location": "Theatre",
	    "duration" : "00:15",
            "title": "Opening Conference, Briefing Day 1", 
            "description": "",
            "attendee": "Jan Lehnhardt, Holger Blank, Malte Ubl",
            "url": "",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-25T09:30:00", 
            "location": "Theatre",
	    "duration" : "00:45",
            "title": "Using the Web to deliver the next wave of computing experiences", 
            "description": "With the mobile world becoming more complex with platforms like Palm webOS, iOS, Android, Blackberry, and Symbian all with growing user bases, how can you build applications that target a wide variety of devices? In the past, the solution was J2ME (boo! ;), but now the common denominator for the smartphones of the world is WebKit, the HTML5-based engine that's powering today's smartphones.",
            "attendee": "Dion Almaer, Ben Galbraith",
            "url": "http://jsconf.eu/2010/speaker/using_the_web_to_deliver_the_n.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-25T10:15:00", 
            "location": "Theatre",
	    "duration" : "00:45",
            "title": "Your library sucks, and why you should use it", 
            "description": "JavaScript Frameworks, Libraries, and Loaders -- there is no shortage of options. Each are wrong. Each have their own philosophies, usefulness, targets, and flaws. Continuing on the It's Just JavaScript theme we'll take a subjective look at the current offerings, what problems they intend to solve, and the reasons you should be using one of them anyway.",
            "attendee": "Peter Higgins",
            "url": "http://jsconf.eu/2010/speaker/your_library_sucks_and_why_you.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-25T10:15:00", 
            "location": "Music School",
	    "duration" : "00:45",
            "title": "HTML5 APIs - The new Frontier", 
            "description": "HTML5 is upon us and it offers a wide range of exciting possibilities when it comes to developing rich web interfaces. This talk will introduce you to a number of them and hopefully inspire you to create amazing things!",
            "attendee": "Robert Nyman",
            "url": "http://jsconf.eu/2010/speaker/html5_apis_-_the_new_frontier.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-25T11:15:00", 
            "location": "Theatre",
	    "duration" : "00:30",
            "title": "JavaScript + Web Standards II: The Quickening", 
            "description": "I will talk about common JavaScript enhanced mistakes that prevent users from enjoying the site experience and provide solutions on how to overcome those. Accessibility and usability should always be on the forefront of your code; this talk will cover take-away tips and general theory all while keeping those goals of best practices in mind.",
            "attendee": "Jenn Lukas",
            "url": "http://jsconf.eu/2010/speaker/javascript_web_standards_ii_th.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-25T11:15:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "Creating Interactive Data Visualizations for the Web", 
            "description": "The Web has never been more open to everyone. Open Data services exist in almost every web application: from social networking apps to governmental pages and the news, all this data can be instantly accessed by exposed APIs. However, although most of this data is offered in a simple interchange format, its structures are quite complex, ranging from complex networks to time-based information, hierarchical data or heavy graphs. Displaying this data in a manner that enables the viewer to gain some insight can be challenging, especially if we aim at providing some interaction and doing it in a cross-browser/cross-device manner. The JavaScript InfoVis Toolkit creates interactive data visualizations for the Web. It's based solely on Web Standards, leveraging the power of native browser technologies to provide insights on complex data. In this talk you will learn about the JavaScript InfoVis Toolkit and how it can help you create advanced data visualizations for the Web.",
            "attendee": "Nicolas Garcia Belmonte",
            "url": "http://jsconf.eu/2010/speaker/creating_interactive_data_visu.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-25T11:45:00", 
            "location": "Theatre",
	    "duration" : "00:30",
            "title": "Techniques and Tools for Taming Tangled Twisted Trains of Thought", 
            "description": "One of the biggest challenges to the otherwise wonderful programming model of JavaScript is handling complex logic that involves lots of async functions and things that emit events. The inversion-of-inversion-of-inversion-of-control often needed is hard to read, write, and just plain understand. With pre-empetive multi-threading you delegate all control to the operating system and it handles concurrency for you. This comes at a great performance cost. However with JavaScript this simply isn't the model, there is one thread and finite snippets of code executed. There is nothing like being able to tell a computer exactly how much code to run and under what conditions and it just works under extreme load and/or concurrency.",
            "attendee": "Tim Caswell",
            "url": "http://jsconf.eu/2010/speaker/techniques_and_tools_for_tamin.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-25T11:45:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "If it moves they will watch it", 
            "description": "Doing animations in the dark ages of the internet led you to technologies like Flash, or even Java Applets. Early arcane magicians tried bending the will of the DOM to create shiny stuff. It felt wrong. With HTML5 two technologies arrived to fix that: Say hi to Canvas and SVG! Our talk will cover basic usage and use cases of both technologies. By showing demos and real world examples we'll try to give you an understanding of when to choose what. Eventually we will show you libraries based on Canvas or SVG which should save you some time.",
            "attendee": "Sebastian Deutsch, Sebastian Seidt",
            "url": "http://jsconf.eu/2010/speaker/if_it_moves_they_will_watch_it.html",
            "pbfeventid" : 0},
            {
            "dtstart": "2010-09-25T12:15:00", 
            "location": "Theatre",
	    "duration" : "00:30",
            "title": "Server-side JavaScript the untold story", 
            "description": "Did you know that London 2012 olympics shop runs on server-side JavaScript? Did you know that you can buy a Burton snowboard, a Puma sneaker or latest fashion from Nine West, all with the help from server-side JavaScript. All these web sites run on Demandware's commerce platform, where customization from business logic to pages is done with JavaScript. The talk gives an introduction how JavaScript is used on the Demandware platform and talks about the history, the decision made along the way, the learning and the DOs and DON'Ts with server-side JavaScript in a system, which is provided in a platform-as-a-service model",
            "attendee": "Ulrike Müller",
            "url": "http://jsconf.eu/2010/speaker/server-side_javascript_the_unt.html",
            "pbfeventid" : 0},
            {
            "dtstart": "2010-09-25T12:15:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "Aves Engine: High performance browser games", 
            "description": "Graphically intensive and fast paced browser games written in pluginless JavaScript largely do not exist yet, for a very specific reason - Performance issues. Only recently, browser engines started to give us enough quirks and hacks to power full motion graphics, animation and real time interaction. With unprecedented depth, you'll learn why Canvas isn't the obvious choice, why you should write JavaScript in front- and backend, why HTML5 really is just a buzzword and how to leverage CSS hardware accelerated to create true platform independent games. Dive in to the world of JavaScript gaming!",
            "attendee": "Paul Bakaus",
            "url": "http://jsconf.eu/2010/speaker/aves_engine_high_performance_b.html",
            "pbfeventid" : 0},
             {
            "dtstart": "2010-09-25T13:45:00", 
            "location": "Theatre",
	    "duration" : "00:45",
            "title": "CSS Lint for Massive Sites", 
            "description": "You like the idea of Object Oriented CSS, but your website has out-of-control CSS bloat. You know your performance is being impacted, but how do you move from organic CSS with no particular architecture to something lighter, more logical, and easier to maintain? How do we automate some of the heavy-lifting and stop wasting our own time? CSS is typically the most difficult layer to automate, but a more clearly defined CSS architecture makes lint much more powerful. In this session, Nicole will show you how she improved the CSS at Facebook and demo tools that you can use to test your own CSS.",
            "attendee": "Nicole Sullivan",
            "url": "http://jsconf.eu/2010/speaker/css_lint_for_massive_sites.html",
            "pbfeventid" : 0},
            {
            "dtstart": "2010-09-25T13:45:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "node.js + CouchDB == Crazy Delicious", 
            "description": "For a variety of reasons CouchDB and node.js are a perfect fit. This talk will focus on node.js tools and utilities for accessing CouchDB, writing Couchapps and responding to _changes events.",
            "attendee": "Mikeal Rogers",
            "url": "http://jsconf.eu/2010/speaker/nodejs_couchdb_crazy_delicious.html",
            "pbfeventid" : 0},
            {
            "dtstart": "2010-09-25T14:15:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "Dirty NoSQL", 
            "description": "What would happen if your database would have no network interface, no query abstractions and less than 250 lines of node.js code? You would end up with a very flexible in-memory database that is wonderfully suitable for dirty tasks such as rapid prototyping or performing millions of GET/SET operations per second. This talk is about rethinking current database technology and exploring situation-based CAP tradeoffs.",
            "attendee": "Felix Geisendörfer",
            "url": "http://jsconf.eu/2010/speaker/dirty_nosql.html",
            "pbfeventid" : 0},
            {
            "dtstart": "2010-09-25T14:30:00", 
            "location": "Theatre",
	    "duration" : "00:45",
            "title": "PhoneGap: Love the Web and Lose the SDK", 
            "description": "Building native mobile applications across platforms with PhoneGap is super easy but developers are still required to install a dizzying array of SDKs for: iOS, Android, Blackberry, webOS, Symbian, MeeGo and Windows Phone. At JSConf.eu the PhoneGap team is releasing a special sneak peak at two new projects which aim to solve this problem. Unlike our previous sessions which have been information dense lightened up with pixel art and 4chan pictures this session will be more code intense: with pixel art and 4chan pictures!",
            "attendee": "Brian LeRoux",
            "url": "http://jsconf.eu/2010/speaker/phonegap_love_the_web_and_lose.html",
            "pbfeventid" : 0},
            {
            "dtstart": "2010-09-25T14:45:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "node.js in production use: tempalias.com", 
            "description": "In order to find out whether node.js is ready for production use and to scratch an itch, tempalias.com was started as a fun project. The service allows anybody to create a temporary email alias with a limited validity (either time- oder usage based). Mail sent to that alias within the validity constraints is then forwarded to any address of your choice. The talk gives a behind-the-scenes look on how the (free software) project was built and how its architecture works. On the process, we'll learn how to build a web application without dynamically generating a single byte of HTML on the server side, how SMTP works, and how to implement a bookmarklet without destroying arbitrary target pages. And we'll learn how to design a daemon in a way sure to bring your server down under load :-)",
            "attendee": "Philip Hofstetter",
            "url": "http://jsconf.eu/2010/speaker/nodejs_in_production_use_tempa.html",
            "pbfeventid" : 0},
            {
            "dtstart": "2010-09-25T15:30:00", 
            "location": "Theatre",
	    "duration" : "00:20",
            "title": "Lessons learnt pushing browsers to the limit", 
            "description": "Applications that were once on the desktop are now appearing on the Web, bringing a whole new set of performance challenges. After writing a console emulator in JavaScript, I have a few tips to share that might be applicable to your more sensible applications. I will talk about the differences in performance between modern browsers, tweaks that can have a huge impact on the speed of your code, and some fun hacks",
            "attendee": "Ben Firshman",
            "url": "http://jsconf.eu/2010/speaker/lessons_learnt_pushing_browser.html",
            "pbfeventid" : 0},
            {
            "dtstart": "2010-09-25T15:30:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "Better Life with shared ressources", 
            "description": "Scalable Vector Graphics can be scripted easily, avoiding Flash by the way. Also, scripting across multimple domains has always been an issue. Developers need to know how to break the security limitations of common browsers in order to build great web services. In JavaScript, dealing with large volumes of data can dramatically slow down the browser performance - the third hard issue. This session gives you a quick pack of solutions that dramatically speed up your web development.",
            "attendee": "Markus Franz",
            "url": "http://jsconf.eu/2010/speaker/better_life_with_shared_resour.html",
            "pbfeventid" : 0},
            {
            "dtstart": "2010-09-25T15:50:00", 
            "location": "Theatre",
	    "duration" : "00:20",
            "title": "Not your Mother's JavaScript!", 
            "description": "JavaScript was made for the web of yesterday, but the web has changed significantly in the past decade and therefore the requirements of a JavaScript for tomorrow. I'm a JavaScript hacker and its in the nature of hackers that having a better language tomorrow isn't fast enough for us. Let me show you how to deal with the flexibility of today's JavaScript implementations to make things, which you may haven't seen before running in a Browser but will definitely become needed parts for the future of web development. This will be about shifting bits and bytes, misusing native file formats, overloading operators, uncommon using of getters/setters and some more evil JavaScript hackery.",
            "attendee": "Tobias Schneider",
            "url": "http://jsconf.eu/2010/speaker/not_your_mothers_javascript.html",
            "pbfeventid" : 0},
            {
            "dtstart": "2010-09-25T16:00:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "Rapid Prototyping for Multiple Platforms with JavaScript", 
            "description": "This topic will cover the concept of what rapid prototyping is, why it is important in the design and development process, and how you can not only leverage the power of JavaScript to rapidly develop proof of concepts and prototypes, but build them with multiple devices in mind.",
            "attendee": "Joe McCann",
            "url": "http://jsconf.eu/2010/speaker/rapid_prototyping_for_multiple.html",
            "pbfeventid" : 0},
            {
            "dtstart": "2010-09-25T16:10:00", 
            "location": "Theatre",
	    "duration" : "00:20",
            "title": "Using canvas to develop classic 2D games", 
            "description": "With recent advancements in JavaScript interpreters it's possible to run more complex games inside the Browser, using JavaScript and the canvas tag. In this talk, we'll explore what is needed to develop a 2D game, like Monkey Island, entirely in JavaScript, by example of JSScummVM, a (work in progress) JavaScript port of the adventure game engine ScummVM. Some of the topics covered are: palette graphics, Sprites, manipulating canvas image data, Blitters, Timing, Sound and new technologies like WebGL and Chrome's Native Client.",
            "attendee": "Mutwin Kraus",
            "url": "http://jsconf.eu/2010/speaker/using_to_develop_classic_2d_ga.html",
            "pbfeventid" : 0},
            {
            "dtstart": "2010-09-25T16:30:00", 
            "location": "Theatre",
	    "duration" : "00:30",
            "title": "The jQuery Divide", 
            "description": "Project managers, bosses, and teams are picking jQuery as their go-to JavaScript library at an ever-increasing pace. Nobody wants to choose a loser, and as demonstrated by super-meaningful Google graphs and surveys that count my grandfather's blog alongside leading web sites, jQuery is leaving all the other libraries in the dust. Plus, it's easy! And there's a plugin for everything! And with all those sites using it, finding someone who can write thoughtful, maintainable code with it will be totally no big deal. Right? This talk is a call to arms. This is not just JavaScript -- it's JavaScript, damnit, a language worthy of respect and, *gasp*, knowledgeable developers. When well-meaning but uninformed deciders and developers see jQuery as the be-all-end-all answer, conflating a knowledge of jQuery with a knowledge of JavaScript, we all lose. As a community, we owe it to the language -- and ourselves -- to give those deciders and developers the context they need to make well-informed decisions. Maybe jQuery is the right answer; but first, they need to truly understand the question.",
            "attendee": "Rebecca Murphy",
            "url": "http://jsconf.eu/2010/speaker/the_jquery_divide_by_rebecca_m.html",
            "pbfeventid" : 0},
            {
            "dtstart": "2010-09-25T16:30:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "Kick ass code editing and end-to-end JavaScript debugging", 
            "description": "At ajax.org our goal is to create a completely web based IDE. Of course one of the key features is a code editor that developers really enjoy to use. The ajax.org code editor (ACE) uses the DOM for rendering and doesn't depend on any external JavaScript library. It is capable of working with huge documents even in older browsers like IE6. In this talk I will demonstrate the features developers are interested in. For example code completion, syntax highlight, toggle comment, auto indent/outdent or moving/copying lines. Further I will take a look under the cover and show how it is implemented so every attendee can start hacking on it right away. Another important feature of the IDE will be the integrated debugger. With this debugger developers are able to debug node.js and Chrome and thus have an end to end JavaScript debugging solution. I will show how this is acomplished and demonstrate how to debug a node.js server with a JavaScript client running in Chrome.",
            "attendee": "Fabian Jakobs",
            "url": "http://jsconf.eu/2010/speaker/kick_ass_code_editing_and_end.html",
            "pbfeventid" : 0},
            {
            "dtstart": "2010-09-25T17:15:00", 
            "location": "Theatre",
	    "duration" : "00:45",
            "title": "Chakra: Building a new JavaScript Engine for Internet Explorer 9", 
            "description": "Internet Explorer 9 introduces a new JavaScript engine, codenamed Chakra, which fundamentally changes the performance characteristics of JavaScript inside Internet Explorer 9. We'll dive into what's new in Chakra, including the new compiler that compiles JavaScript source code into high-quality native machine code, a new interpreter for executing script on traditional web pages, and improvements to the JavaScript runtime and libraries like ECMAScript 5 support.",
            "attendee": "Pete LePage",
            "url": "http://jsconf.eu/2010/speaker/chakra_building_a_new_javascri.html",
            "pbfeventid" : 0},
            {
            "dtstart": "2010-09-25T18:00:00", 
            "location": "Theatre",
	    "duration" : "00:45",
            "title": "Proxy Objects", 
            "description": "Proxy Objects are going to an amazing new addition to the next version of ECMAScript. You will be able to allow a proxy to intercede any method or internal within the ECMA specification, allowing you to wrap everything in the JavaScript object domain. This is super powerful for logging, debugging, operation inversion, and if you can wrap the entire DOM and record timestamps, this might be the magic bullet that will allow you record and replay DOM interactions. We are bringing metaprogramming or Meta Object Programming to JavaScript and this will be your first peek at this awesome technology.",
            "attendee": "/be",
            "url": "http://jsconf.eu/2010/speaker/be_proxy_objects.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-25T18:45:00", 
            "location": "Theatre",
	    "duration" : "00:15",
            "title": "Closing Day 1", 
            "description": "",
            "attendee": "Jan Lehnhardt, Holger Blank, Malte Ubl",
            "url": "",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T09:45:00", 
            "location": "Theatre",
	    "duration" : "00:15",
            "title": "Opening Day 2", 
            "description": "",
            "attendee": "Jan Lehnhardt, Holger Blank, Malte Ubl",
            "url": "",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T10:00:00", 
            "location": "Theatre",
	    "duration" : "01:00",
            "title": "Loopage", 
            "description": "Software development is hampered by a specific set of design mistakes that were made in the first programming languages and repeated in everything that has been done since. And, somewhat miraculously, JavaScript is going to make it right, radically transforming the way we write applications. Again. In the Loop of History, it has all happened before, but it has never happened like this.",
            "attendee": "Douglas Crockford",
            "url": "http://jsconf.eu/2010/speaker/loopage_by_douglas_crockford.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T11:00:00", 
            "location": "Theatre",
	    "duration" : "00:30",
            "title": "The hitchhiker's guide to client side persistent data storage", 
            "description": "Plugin-independent client side data storage, like HTML5 powered localStorage or IndexedDB, is becoming more relevant every day, though it had been there for ages. In fact, IE 5.5 was the first browser to offer data persistence in other forms than cookies. However, today, as we are online most of our time, handling offline situations has become important for many web apps. And for mobile dev, storage is crucial: You wouldn't want to pull some hundred k of data via a slow connection again and again. This talk will take a tour around existing client side storage mechanisms. We'll start with cookies and see why it's a bad place to stay. Then we'll quickly move on to the good neighbours, visiting ancient places as well as futuristic ones and investigating their ins and outs. And we'll also stop by the frameworks/wrappers that give easy access to them. To make things more interesting, we'll then board a submarine and dive into the crazy world of mobile devices, it's special demands and see what options exist over there. Finally, we'll have a look at performance and security concerns. Don't forget your towel!",
            "attendee": "Jens Arps",
            "url": "http://jsconf.eu/2010/speaker/the_hitchhikers_guide_to_clien.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T11:00:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "The State of HTML5: Inaugural Address", 
            "description": "HTML5 and friends have been getting implemented in browsers at an impressively quick pace. But that leaves us as web developers wondering: Great, but how am I supposed to build cross-browser applications with these features when I still have to support IE? We'll take a look at what the landscape of implementable features are, detailing best practices of implementation and fallback solutions where appropriate. For example, how do you pair WebSockets with a standard comet stack and what do you have to watch out for. We'll also review your available feature set if you're only targeting webkit mobile, or if you've already given IE6 the boot. The data will be up-to-the-day accurate, covering all major browsers and filled with best practices from topic experts.",
            "attendee": "Paul Irish",
            "url": "http://jsconf.eu/2010/speaker/the_state_of_html5_inaugural_address_by_paul_irish.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T11:45:00", 
            "location": "Theatre",
	    "duration" : "00:30",
            "title": "Techniques for a single stack world", 
            "description": "Node.js presents the same non-blocking, single execution stack programming model of client-side Javascript. However, Node is arguably aiming at more complex problems than browsers have faced: massively concurrent servers that may shell out to many different processes, that might need to execute many sequential file system operations. Can this programming model support such systems or does the code degenerate into a spaghetti of callbacks? This talk will present an emerging set of patterns being used in this new domain.",
            "attendee": "Ryan Dahl",
            "url": "http://jsconf.eu/2010/speaker/techniques_for_a_single_stack.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T11:45:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "Interface Styling for WebKit Mobile", 
            "description": "Everybody talks about WebKit and you can see a lot of versions and new features coming out every day and even more on mobile. But do you really know about web fonts, hardware accelerated CSS functionality, animations and transitions? In this talk I will show you some of this stuff. You will also learn about the flexible box layout and other niceties which, and I will have proof, do really reduce the size of your CSS code and increase readablity by a lot, which on mobile matters even more. And to make sure that JavaScript doesn't come to short you will see how to script this stuff and make it intergrate in your app. And above all that I will show you where WebKit differs on iOS, Android, webOS and S60.",
            "attendee": "David Aurelio",
            "url": "http://jsconf.eu/2010/speaker/interface_styling_scripting_fo.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T12:15:00", 
            "location": "Theatre",
	    "duration" : "00:30",
            "title": "Getting functional with (fab)", 
            "description": "(fab) is an HTTP framework for that eschews the conventionally muddled web stack of middleware, routers, and handlers for a cleaner, more functional approach. By stressing convention over code, (fab) enables any web app to be recursively composed of other web apps, using a chained pattern that enables the full power of javascript but the simple readability of a site map. In this presentation, Jed will show you how to use (fab) to get up and running with your own reusable apps on both the client and server.",
            "attendee": "Jed Schmidt",
            "url": "http://jsconf.eu/2010/speaker/getting_functional_with_fab.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T12:15:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "Introducing Unify - A Framework for Cross Platform Applications", 
            "description": "",
            "attendee": "Sebastian Werner",
            "url": "http://jsconf.eu/2010/speaker/introducing_unify_-_a_framewor.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T12:45:00", 
            "location": "Theatre",
	    "duration" : "00:30",
            "title": "Don't write spaghetti code in server side JavaScript", 
            "description": "Server Side JavaScript (especially Node.js) is a hot topic right now, but we are still figuring out what good SSJS code looks like. It isn't enough that we can write JavaScript on the server, or even that it is well written JavaScript. It's essential that we write maintainable JavaScript for the server environment. This talk will examine different coding styles for event driven, non-blocking SSJS and which styles are most successful. We'll take a look at strategies that other languages and frameworks with similar attributes such as Clojure, Erlang, Python/Twisted and Ruby/Event Machine use. From these languages we'll take a look what has worked well and what hasn't. We'll explore how these models can apply to JavaScript to create patterns that can be used to make code more maintainable.",
            "attendee": "Tom Hughes-Croucher",
            "url": "http://jsconf.eu/2010/speaker/dont_write_spaghetti_code_in_s.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T12:45:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "Socket.IO: Web Sockets for Everyone", 
            "description": "The realtime web is right around the corner, and JavaScript is here to help, both on the server and the client side. The WebSocket protocol promises to solve the problem of bidirectional communication once and for all, but can we leverage it today? Socket.IO provides an API that enables WebSocket for every browser (IE5.5, IE6, IE7, IE8, Safari, Chrome, Firefox 3-4, Opera 10) and multiple mobile devices (including the iPhone and the iPad). I'll talk about how you can get started using Socket.IO today, how people are using it in production environments, and how to create realtime web applications with just a few lines of code.",
            "attendee": "Guillermo Rauch",
            "url": "http://jsconf.eu/2010/speaker/socketio_websockets_for_everyo.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T14:15:00", 
            "location": "Theatre",
	    "duration" : "00:45",
            "title": "Bespin: The JavaScript Programmer's Editor", 
            "description": "The Mozilla Labs Bespin project has created a customizable code editor that's built on the HTML5 capabilities present in the rapidly expanding list of modern browsers. The project has evolved to support the notion of coding in any cloud, as it's easy to build an editor to include in your own web applications. You can use Bespin in bookmarklet form to improve the editing experience at any site you visit. Finally, the JavaScript-based desktop and server packages allow you to edit code on your local machine or in your own, personal or small group cloud. In this talk, the Mozilla developer tools team will run through what Bespin can do for you, how you can customize it and where the project is headed.",
            "attendee": "Kevin Dangoor, Joe Walker, Patrick Walton",
            "url": "http://jsconf.eu/2010/speaker/bespin_the_javascript_programm.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T14:15:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "Pirating the Sematic Web with JavaScript", 
            "description": "The term Semantic Web has been around forever (well, almost, at least in Internet terms). This talk will provide an introduction to the Semantic Web as it evolves these days, with a strong focus on how to make use of semantically enriched data with JavaScript. We will show real world state-of-the-art examples, and also give an outlook on bleeding edge research on the topic, e.g. the JavaScript RDFa DOM API.",
            "attendee": "Thomas Steiner",
            "url": "http://jsconf.eu/2010/speaker/pirating_the_semantic_web_with.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T14:45:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "The Art of deep linking and AJAX crawling", 
            "description": "Do you want to take your AJAX powered website to the next level by making it easily accessible through deep links? And how about making all the dynamic data available to the major search engines? Come and learn more about all the existing and evolving techniques, the best practices and details that you should have in mind.",
            "attendee": "Rotislav Hristov",
            "url": "http://jsconf.eu/2010/speaker/the_art_of_deep_linking_and_aj.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T15:00:00", 
            "location": "Theatre",
	    "duration" : "00:45",
            "title": "Robotic JavaScript", 
            "description": "Did you dream about writing applications in HTML, JavaScript and CSS which could tell you how much you weigh or what the outside temperature is? What if we had a web-based interface to setup and program all our devices at home? Well, your dreams are heard and finally, today we are able to do all this. In this talk we will walk through the implications of opening up the browsers APIs, explore real life use-cases and will demonstrate working examples which will show that JavaScript, HTML and CSS are the perfect tools to build interfaces controlling and reading hardware. This presentation will highlight various options (like LinuxMCE, Arduino, Lego Mindstorms NXT) for programming hardware, along with a few pratical experiments like scripting a bluetooth-connected Wiimote, a web-enabled socket outlet and interacting with an Arduino board and sensors directly from an iPhone. Code and instructions for each experiment will be available later",
            "attendee": "Jörn Zaefferer, Nikolai Onken",
            "url": "http://jsconf.eu/2010/speaker/livingroombindmotion_function.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T15:15:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "CommonJS, I Promise", 
            "description": "CommonJS 2010 is moving beyond modules. Placing a hold on standards for IO, CommonJS discussions this year have focused on Binary data, Promises, Packages, and more. We've also moved away from ratifying particular proposals and more toward providing a forum for thoughful design. Join Kris for a pointed presentation on the state of CommonJS: what's done, what's being debated, and what needs to be done.",
            "attendee": "Kris Kowal",
            "url": "http://jsconf.eu/2010/speaker/commonjs_i_promise_by_kris_kow.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T16:00:00", 
            "location": "Theatre",
	    "duration" : "00:30",
            "title": "Browser Extensions for Web Hackers", 
            "description": "Building browser extensions is now easier than ever. Jetpack, Chrome and Safari 5 combine open web technologies with a few special APIs and clever design, opening up extension development to any web hacker. In this talk we'll build a few simple extensions for Chrome, introducing the main concepts in their extension system. We'll compare and contrast with Jetpack and Safari 5. Expect working code and a energetic presentation!",
            "attendee": "Mark Wubben",
            "url": "http://jsconf.eu/2010/speaker/browser_extensions_for_web_hac.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T16:00:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "The Front-end Takeover", 
            "description": "With all the talk and hype over server side platforms and technologies, somehow we've been neglecting the most ubiquitous and widely used javascript platform - the browser. Differences aside, the web browser and the desktop are becoming more and more entwined and just generally faster. Now is our chance to make web applications that surpass the usefulness and awesomeness of desktop counterparts. Sure, there are technologies that allow you to bring desktop style code to the web. With Sammy.js, I'm more interested in creating web style apps that can compete as desktop experiences. Sammy.js is a very simple framework for organizing browser based javascript applications. Despite its size, when combined with other cutting edge technologies, (CouchDB, other RESTful DB's, Comet) it becomes a very powerful way to write entirely front-end, entirely JavaScript applications. I'll walk through the basics of Sammy, show some cool examples of Sammy in production, and talk about new features and technologies that make this all a pretty exciting time to be writing JS.",
            "attendee": "Aaron Quint",
            "url": "http://jsconf.eu/2010/speaker/oh_no_not_again.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T16:30:00", 
            "location": "Theatre",
	    "duration" : "00:30",
            "title": "Not your unit test", 
            "description": "I will talk about the different aspects, approaches and tools for testing javascript applications (web and offline, server and client side). There's much more you can do in testing than just writing a bunch of unit tests. To be confident in the code you write you also need to test the interactions between different modules, sometimes even integration with other services. Let me show you how.",
            "attendee": "Alexander Lang",
            "url": "http://jsconf.eu/2010/speaker/not_your_unit_test_by_alexande.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T16:30:00", 
            "location": "Music School",
	    "duration" : "00:30",
            "title": "Srsly R1pp3d J@vaScript", 
            "description": "All the major libraries have ended up looking like jQuery. Now they just bicker about who is the fastest. Library authors stopped innovating 2-3 years ago.' - Dean Edwards. FuseJS is a new JS library that is bringing innovation back, solving problems thought unsolvable and challenging the JS status quo. I will give a brief history of FuseJS and discuss some of the areas FuseJS is innovating including sandboxed natives, event delegation, memory leak plugging, element cloning, feature testing/detection registries & profiling, API design, and customization.",
            "attendee": "John David Dalton",
            "url": "http://jsconf.eu/2010/speaker/srsly_r1pp3d_jvascript_by_john.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T17:15:00", 
            "location": "Theatre",
	    "duration" : "00:45",
            "title": "Performance Patterns", 
            "description": "In this talk Stoyan will share bits of his forthcoming book JavaScript Patterns (published O'Reilly) focusing on performance. How do we evaluate and measure performance and patterns to improve and write high-performance JavaScript.",
            "attendee": "Stoyan Stefanov",
            "url": "http://jsconf.eu/2010/speaker/performance_patterns_by_stoyan.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T18:00:00", 
            "location": "Theatre",
	    "duration" : "00:45",
            "title": "Community.js", 
            "description": "Despite being around and prevalent for over 10 years, JS has only recently come to enjoy a focused community. We pull from all ends of the technology spectrum, we do amazing things, and most importantly we JSConf. That all said, we need to make a commitment to growing the community in the right way, with the right blend of inclusivity and awesome. It is our charge to ensure that the world sees JS as a viable option and more importantly a vibrant and welcoming community. Despite our preference in library, despite our preference in framework, there has to be one unifying thing that brings us together - and it can't JUST be a common hatred for IE6. I opened the doors to something important with the first JSConf, and with this talk I am starting the discussion for what the JS Community is, means, and how we want it to be viewed. Unlike any other programming language, our community is completely homegrown, organic, and driven by grassroots efforts like JSConf (eu|us). It is up to us, developers, to do something amazing here and it would be our folly to not learn from all other language communities, else we are destined to become like them.",
            "attendee": "Chris Williams",
            "url": "http://jsconf.eu/2010/communityjs_by_chris_williams.html",
            "pbfeventid" : 0},
	    {
            "dtstart": "2010-09-26T18:45:00", 
            "location": "Theatre",
	    "duration" : "00:15",
            "title": "Closing Conference, Instructions for Party", 
            "description": "",
            "attendee": "Jan Lehnhardt, Holger Blank, Malte Ubl",
            "url": "",
            "pbfeventid" : 0}
            ]
};